import PeoplesIcon from './Photos/peoples.svg'
import LocationIcon from './Photos/location.svg'
import GraphImp from './Photos/graphImpress.svg'
import GraphCont from './Photos/graphCont.svg'
import Impressions from './Photos/impressions.svg'
import Contributions from './Photos/contributions.svg'
import RVNode from './Photos/RVNode.svg'
import RVClub from './Photos/RVClub.svg'
import DebateIcon from './Photos/Debate.svg'
import RulesIcon from './Photos/Rules.svg'
import Mplace from './Photos/Mplace.svg'
import ForwardIcon from './Photos/forward.svg'
import NodeProf1 from './Photos/Nodephoto.png'
import NodeProf2 from './Photos/NodeProf2.png'
import NodeProf3 from './Photos/NodeProf3.png'
import ClubProf1 from './Photos/ClubProf1.png'
import ClubProf2 from './Photos/ClubProf2.png'
import ClubProf3 from './Photos/ClubProf3.png'
import ClubProf4 from './Photos/ClubProf4.png'
import ClubProf5 from './Photos/ClubProf5.png'
 
export {PeoplesIcon, LocationIcon, NodeProf1, NodeProf2, NodeProf3, GraphCont, GraphImp, Impressions, Contributions, RVClub, RVNode, DebateIcon, RulesIcon, Mplace, ForwardIcon, ClubProf1, ClubProf2, ClubProf3, ClubProf4, ClubProf5}